//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockRanking.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection WeightsValues {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["WeightsValues"]));
            }
            set {
                this["WeightsValues"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size FormSizeBacktest {
            get {
                return ((global::System.Drawing.Size)(this["FormSizeBacktest"]));
            }
            set {
                this["FormSizeBacktest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size FormSizeStrategy {
            get {
                return ((global::System.Drawing.Size)(this["FormSizeStrategy"]));
            }
            set {
                this["FormSizeStrategy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size FormSizeScatterplot {
            get {
                return ((global::System.Drawing.Size)(this["FormSizeScatterplot"]));
            }
            set {
                this["FormSizeScatterplot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size FormSizeRealtimeView {
            get {
                return ((global::System.Drawing.Size)(this["FormSizeRealtimeView"]));
            }
            set {
                this["FormSizeRealtimeView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int RefreshInterval {
            get {
                return ((int)(this["RefreshInterval"]));
            }
            set {
                this["RefreshInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExpectedPortfolioCols {
            get {
                return ((string)(this["ExpectedPortfolioCols"]));
            }
            set {
                this["ExpectedPortfolioCols"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CurrentPortfolioCols {
            get {
                return ((string)(this["CurrentPortfolioCols"]));
            }
            set {
                this["CurrentPortfolioCols"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CompositeGraphMetrics {
            get {
                return ((string)(this["CompositeGraphMetrics"]));
            }
            set {
                this["CompositeGraphMetrics"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size PerformanceTableSize {
            get {
                return ((global::System.Drawing.Size)(this["PerformanceTableSize"]));
            }
            set {
                this["PerformanceTableSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PerformanceTableSeparator {
            get {
                return ((int)(this["PerformanceTableSeparator"]));
            }
            set {
                this["PerformanceTableSeparator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LSQt2S1x-abvHTx_Lavx")]
        public string ApiKey1 {
            get {
                return ((string)(this["ApiKey1"]));
            }
            set {
                this["ApiKey1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ZcwnLyzQDy6JqsHyqMGx")]
        public string ApiKey2 {
            get {
                return ((string)(this["ApiKey2"]));
            }
            set {
                this["ApiKey2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pk_43a4dbce69d3491fab5f2c3d6a8b3db3")]
        public string ApiKey3 {
            get {
                return ((string)(this["ApiKey3"]));
            }
            set {
                this["ApiKey3"] = value;
            }
        }
    }
}
